name: petct
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Provider library
  provider: ^4.0.0
  # Streaming package
  rxdart: ^0.23.0
  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^3.0.0
  # Value equality
  equatable: ^1.0.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.6
  # Internationalization
  internationalization: ^2.0.0
  # Firebase Dependencies
  firebase_database: ^3.1.1
  firebase_auth: ^0.16.0
  # Pdf
  pdf: 1.8.1
  # Path Provider
  path_provider: ^1.6.10
  # Full PDF Viewer
  flutter_full_pdf_viewer: ^1.0.6
  # Feather Icons
  feather_icons_flutter: ^4.7.4
  #Share Extend
  share_extend: ^1.1.7
  #Mobx
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  #Google Fonts
  google_fonts: ^1.1.0
  #Flutter Svg
  flutter_svg: ^0.19.3
  #Percent indicator
  percent_indicator: ^2.1.7+4

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  mobx_codegen: 
  build_runner: 
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - assets/images/
  - assets/strings/
  - internationalization.yaml